Test iteration four
Lexamenrf44/ABarashkov_Java_Selenide_SauceDemo_Project pull request #6
Opened 2024-11-28 10:55 UTC by Lexamenrf44

2024-11-28 12:39 UTC, mipkasnow requested changes
ревью провел

2024-11-28 12:39 UTC, mipkasnow commented on .gitignore
> +src/test/resources/screenshots/
Ты зачем-то в гитигнор добавил директорию, в которой хранятся наши скриншоты)

2024-11-28 12:39 UTC, mipkasnow commented on src/test/java/com/saucedemo/pages/ItemsPage.java
> +        return null;
Все же тут не хотелось бы оставлять так, коль скоро ты отнаследовался от BasePage - надо метод checkThatPageLoaded явно реализовать, а не оставлять return null

2024-11-28 13:24 UTC, Lexamenrf44 commented on .gitignore
> +src/test/resources/screenshots/
Resolved

2024-12-01 18:52 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/ItemsPage.java
> +        return null;
Fixed;

2024-12-01 18:52 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/ItemsPage.java
> +        manuallyClearCookies();
Fixed;

2024-12-01 18:53 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/LoginPage.java
> +        return null;
Fixed;

2024-12-01 18:53 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/tests/CookiesAuthTest.java
>      }
Fixed;

2024-12-01 18:53 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/utils/ScreenshotUtils.java
> +    }
Fixed during class work;

2024-12-01 18:53 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/utils/ScreenshotUtils.java
> +        }
Fixed during class work;

2024-12-01 18:53 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/utils/ScreenshotUtils.java
> +            ImageIO.write(diffImage, "png", diffFile);
Fixed during class work;

2024-12-01 18:54 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/utils/ScreenshotUtils.java
> +            ObjectMapper objectMapper = new ObjectMapper();
Fixed during class work;

2024-12-01 19:08 UTC, mipkasnow requested changes

2024-12-01 19:08 UTC, mipkasnow commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        burgerMenuButton.shouldBe(visible).click();
burgerMenuButton.shouldBe(visible).click(); - нет никакого смысла вызывать shouldbe visible перед методом click. Заходим в метод click и там написано - Before clicking, waits until element gets interactable and enabled.
Так что проверка на видимость в селениде идет автоматичемски при любом взаимодействии с элементами

2024-12-01 19:08 UTC, mipkasnow commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        logoutSideBarButton.shouldBe(visible).click();
думаю слайдер идеальный момент для создания компонента - нужно вынести всю работу со слайдером в отдельный класс

2024-12-01 19:08 UTC, mipkasnow commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        return new LoginPage().checkThatPageLoaded();
идея понятна, но плохо, что слип тут захардкожен

2024-12-01 19:11 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/CartPage.java
> +    @Step("Check that Login Page is visible")
fixed;

2024-12-01 19:13 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        burgerMenuButton.shouldBe(visible).click();
Fixed;

2024-12-02 00:47 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        logoutSideBarButton.shouldBe(visible).click();
Fixed;

2024-12-02 00:52 UTC, Lexamenrf44 commented on src/test/java/com/saucedemo/pages/InventoryPage.java
> +        return new LoginPage().checkThatPageLoaded();
Fixed;

2024-12-02 00:52 UTC, merged